version: "3"

services:
  ontime:
    container_name: ontime
    image: getontime/ontime:latest
    ports:
      - "4001:4001/tcp"
      - "8888:8888/udp"
      - "9999:9999/udp"
    volumes:
      - "${HOME}/show-pi/ontime-data:/data/"
      - /etc/localtime:/etc/localtime:ro
# To set a Specifi Time Zone, comment out the '/etc/localtime...' above this line.
#   environment:
#     - TZ=America/Los_Angeles
    restart: unless-stopped
